/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.adso39.vistas;

import com.adso39.controladores.ControlUsuarios;
import com.adso39.modelos.Usuario;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SENA
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    private ControlUsuarios elControlUsuarios;
    /**
     * Creates new form PantallaPrincipal
     */
    
    
    
    public PantallaPrincipal() {
        //this.elControlUsuarios = new ControlUsuarios();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblgestiondeusuario = new javax.swing.JLabel();
        lblidentificacion = new javax.swing.JLabel();
        lblnombre = new javax.swing.JLabel();
        lblapellidos = new javax.swing.JLabel();
        lblcargo = new javax.swing.JLabel();
        lbladministrador = new javax.swing.JLabel();
        txtidentificacion = new javax.swing.JTextField();
        txtnombres = new javax.swing.JTextField();
        txtapellidos = new javax.swing.JTextField();
        checkboxadministrador = new javax.swing.JCheckBox();
        comboboxcargo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        textareagrande = new javax.swing.JTextArea();
        btncapturarinfo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnc5 = new javax.swing.JButton();
        btnAgregUser = new javax.swing.JButton();
        btnListUser = new javax.swing.JButton();
        btnControlUser = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbUsuarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        lblgestiondeusuario.setBackground(new java.awt.Color(153, 0, 153));
        lblgestiondeusuario.setText("GESTIÓN DE USUARIOS=");

        lblidentificacion.setForeground(new java.awt.Color(51, 51, 51));
        lblidentificacion.setText("Identificación:");

        lblnombre.setForeground(new java.awt.Color(51, 51, 51));
        lblnombre.setText("Nombres:");

        lblapellidos.setForeground(new java.awt.Color(51, 51, 51));
        lblapellidos.setText("Apellidos:");

        lblcargo.setForeground(new java.awt.Color(51, 51, 51));
        lblcargo.setText("Cargo:");

        lbladministrador.setForeground(new java.awt.Color(51, 51, 51));
        lbladministrador.setText("Es Administrador:");

        txtidentificacion.setBackground(new java.awt.Color(255, 246, 246));
        txtidentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidentificacionActionPerformed(evt);
            }
        });

        txtnombres.setBackground(new java.awt.Color(255, 245, 245));

        txtapellidos.setBackground(new java.awt.Color(255, 246, 246));

        checkboxadministrador.setBackground(new java.awt.Color(255, 204, 255));
        checkboxadministrador.setText("jCheckBox1");

        comboboxcargo.setBackground(new java.awt.Color(255, 204, 255));
        comboboxcargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        textareagrande.setBackground(new java.awt.Color(255, 241, 241));
        textareagrande.setColumns(20);
        textareagrande.setLineWrap(true);
        textareagrande.setRows(5);
        jScrollPane1.setViewportView(textareagrande);

        btncapturarinfo.setBackground(new java.awt.Color(255, 204, 255));
        btncapturarinfo.setText("Capturar Información");
        btncapturarinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncapturarinfoActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 204, 255));
        jButton1.setText("Capturar informacion objeto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 204, 255));
        jButton2.setText("Capturar informacion obj-Constructor");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 204, 255));
        jButton3.setText("Capturar informacion objcontrol");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnc5.setBackground(new java.awt.Color(255, 204, 255));
        btnc5.setText("Capturar informaciion obj- estatico");
        btnc5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnc5ActionPerformed(evt);
            }
        });

        btnAgregUser.setBackground(new java.awt.Color(255, 204, 255));
        btnAgregUser.setText("Agregar usuario");
        btnAgregUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregUserActionPerformed(evt);
            }
        });

        btnListUser.setBackground(new java.awt.Color(255, 204, 255));
        btnListUser.setText("Listar usuarios");
        btnListUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListUserActionPerformed(evt);
            }
        });

        btnControlUser.setBackground(new java.awt.Color(255, 204, 255));
        btnControlUser.setText("Control Usuario");
        btnControlUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnControlUserActionPerformed(evt);
            }
        });

        tbUsuarios.setBackground(new java.awt.Color(255, 235, 235));
        tbUsuarios.setForeground(new java.awt.Color(255, 204, 204));
        tbUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbUsuarios.setSelectionBackground(new java.awt.Color(204, 204, 255));
        jScrollPane2.setViewportView(tbUsuarios);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblnombre)
                            .addComponent(lblidentificacion))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblapellidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbladministrador)
                                .addGap(18, 18, 18)
                                .addComponent(checkboxadministrador))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtnombres, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtidentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(129, 129, 129)
                                            .addComponent(jButton2))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton1)
                                            .addGap(19, 19, 19))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblgestiondeusuario)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btncapturarinfo)
                                    .addGap(32, 32, 32)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblcargo)
                                .addGap(15, 15, 15)
                                .addComponent(comboboxcargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(509, 509, 509)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnListUser)
                                    .addComponent(btnAgregUser)
                                    .addComponent(btnControlUser))))
                        .addGap(72, 72, 72))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnc5)
                    .addComponent(jButton3))
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 804, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lblgestiondeusuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblidentificacion)
                            .addComponent(txtidentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblnombre)
                            .addComponent(txtnombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblapellidos)
                            .addComponent(txtapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(95, 95, 95)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblcargo)
                            .addComponent(comboboxcargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbladministrador)
                            .addComponent(checkboxadministrador))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btncapturarinfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnc5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnListUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAgregUser)
                        .addGap(18, 18, 18)
                        .addComponent(btnControlUser)))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtidentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidentificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidentificacionActionPerformed

    private void btncapturarinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncapturarinfoActionPerformed
String identificacion = txtidentificacion.getText ();
String nombres = txtnombres.getText ();
String apellidos = txtapellidos.getText ();
int indiceCargo = comboboxcargo.getSelectedIndex();
String textoCargo = comboboxcargo.getSelectedItem().toString();
boolean esAdministrador = checkboxadministrador.isSelected ();

String textoMostrar = "Identificacion: " + identificacion + "\n" +
"Nombre Completo: " + nombres + " " + apellidos + "\n" + 
        "Cargo: (" + indiceCargo + ") " + textoCargo + "\n";
        
        if (esAdministrador) {
            textoMostrar += "El usuario es administrador";
            
        }
        else{
        textoMostrar += "El usuario no es administrador";
        }
        
        textareagrande.setText(textoMostrar);
    }//GEN-LAST:event_btncapturarinfoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Usuario elUsuario = new Usuario();
        String identificacion = txtidentificacion.getText ();
        String nombres = txtnombres.getText ();
        String apellidos = txtapellidos.getText ();
        int indiceCargo = comboboxcargo.getSelectedIndex();
        String textoCargo = comboboxcargo.getSelectedItem().toString();
        boolean esAdministrador = checkboxadministrador.isSelected ();

        elUsuario.setIdentificacion(identificacion);
        elUsuario.setNombres(nombres);
        elUsuario.setApellidos(apellidos);
        elUsuario.setIndiceCargo(indiceCargo);
        elUsuario.setTextoCargo(textoCargo);
        elUsuario.setEsAdministrador(esAdministrador);

        textareagrande.setText(elUsuario.toString());

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Usuario elUsuario = new Usuario(txtidentificacion.getText (),
        txtnombres.getText (),
        txtapellidos.getText (),
        comboboxcargo.getSelectedIndex(),
        comboboxcargo.getSelectedItem().toString(),
        checkboxadministrador.isSelected ());

        
        textareagrande.setText(elUsuario.toString());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       this.elControlUsuarios.RegistrarUsuario(txtidentificacion.getText (),
        txtnombres.getText (),
        txtapellidos.getText (),
        comboboxcargo.getSelectedIndex(),
        comboboxcargo.getSelectedItem().toString(),
        checkboxadministrador.isSelected ());

        
        textareagrande.setText(this.elControlUsuarios.ImprimirUsuario());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnc5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnc5ActionPerformed
        ControlUsuarios.RegistrarUsuario(txtidentificacion.getText (),
        txtnombres.getText (),
        txtapellidos.getText (),
        comboboxcargo.getSelectedIndex(),
        comboboxcargo.getSelectedItem().toString(),
        checkboxadministrador.isSelected ());

        
        textareagrande.setText(this.elControlUsuarios.ImprimirUsuario());
    }//GEN-LAST:event_btnc5ActionPerformed

    private void btnAgregUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregUserActionPerformed
        ControlUsuarios.AgregarUsuario(txtidentificacion.getText(), 
                txtnombres.getText(), 
                txtapellidos.getText(), 
                comboboxcargo.getSelectedIndex(), 
                comboboxcargo.getSelectedItem().toString(),
                checkboxadministrador.isSelected());
        
        textareagrande.setText("Agregado:\n" +
        txtnombres.getText() +
        " " +
        txtapellidos.getText());
    }//GEN-LAST:event_btnAgregUserActionPerformed

    private void btnListUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListUserActionPerformed
        textareagrande.setText(ControlUsuarios.ListarUsuarios());
    }//GEN-LAST:event_btnListUserActionPerformed

    private void btnControlUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControlUserActionPerformed
       ArrayList<Usuario> losUsuarios = ControlUsuarios.MostrarUsuarios();
       
       DefaultTableModel modeloUsuarios = new DefaultTableModel ();
       modeloUsuarios.addColumn("Identificacion");
       modeloUsuarios.addColumn("Nombre completo");
       modeloUsuarios.addColumn("Es administrador");
       for (int index = 0;
               index<losUsuarios.size();
               index++) {
           Object[] fila = new Object[4];
           fila[0] = losUsuarios.get(index).getIdentificacion();
            fila[1] = losUsuarios.get(index).getNombres() + "" +
                    losUsuarios.get(index).getApellidos ();
            if (losUsuarios.get(index).isEsAdministrador()){
                fila[2] = "Si";
            }else {
                fila[2] = "No";
                
            }
            
            modeloUsuarios.addRow(fila);
            
       }
       
       tbUsuarios.setModel (modeloUsuarios);
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
    }//GEN-LAST:event_btnControlUserActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregUser;
    private javax.swing.JButton btnControlUser;
    private javax.swing.JButton btnListUser;
    private javax.swing.JButton btnc5;
    private javax.swing.JButton btncapturarinfo;
    private javax.swing.JCheckBox checkboxadministrador;
    private javax.swing.JComboBox<String> comboboxcargo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbladministrador;
    private javax.swing.JLabel lblapellidos;
    private javax.swing.JLabel lblcargo;
    private javax.swing.JLabel lblgestiondeusuario;
    private javax.swing.JLabel lblidentificacion;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JTable tbUsuarios;
    private javax.swing.JTextArea textareagrande;
    private javax.swing.JTextField txtapellidos;
    private javax.swing.JTextField txtidentificacion;
    private javax.swing.JTextField txtnombres;
    // End of variables declaration//GEN-END:variables
}
